{"uuid": "772972a7-aa13-4c54-a64b-8aa0847fa365", "children": ["b970f8b7-c1c2-4455-b141-fb6b25d47518"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Devel\\python_test\\conftest.py\", line 21, in app\n    fixture = Application(base_url=target['betav11'])\n  File \"C:\\Devel\\python_test\\fixture\\application.py\", line 27, in __init__\n    self.wd = webdriver.Remote(command_executor='http://localhost:4444/wd/hub',\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\packages\\six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"C:\\Devel\\python_test\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"C:\\Program Files\\Python310\\lib\\http\\client.py\", line 1374, in getresponse\n    response.begin()\n  File \"C:\\Program Files\\Python310\\lib\\http\\client.py\", line 318, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Program Files\\Python310\\lib\\http\\client.py\", line 287, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1680158168256, "stop": 1680158229843}], "start": 1680158168256, "stop": 1680158230279}